services:
  - type: web
    name: kallanum-policum
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT kallanum_policum.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: kallanum-policum-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 1

databases:
  - name: kallanum-policum-db
    databaseName: kallanum_policum
    user: kallan_user

